### ISSUE TITLE
Wymyślenie nazw achievementów (osiągnięć)

### ISSUE THREAD

**Issue by GTrela** [CBoola/clicker-frontend#33]

**Comment by jnkgregory** [comment]
Ok.

**Comment by jnkgregory** [comment]
Nazwy Achievment'ów - zrobione.

[Achievments_nazwy.pdf](https://github.com/CBoola/clicker-frontend/files/999244/Achievments_nazwy.pdf)

**Comment by jnkgregory** [comment]
Acievment'y na posiadanie i wydawanie cebuli:

[Achievmenty_Posiadanie_Wydawanie.pdf](https://github.com/CBoola/clicker-frontend/files/999301/Achievmenty_Posiadanie_Wydawanie.pdf)
